# Official JUCE d3d7d4c89c5547c09ff28d7ab13d9f3bccc8595e (JUCE 8.0.5).
# Backport only the Windows pacing fix; keep the rest of JUCE 8.0.4 unchanged.
set(DUCK_VBLANK_FIX_DIR "${CMAKE_CURRENT_LIST_DIR}")
function(duck_apply_windows_vblank_fix juce_root)
 set(target "${juce_root}/modules/juce_gui_basics/native/juce_VBlank_windows.cpp")
 file(READ "${target}" source)
 string(REPLACE "\r\n" "\n" source "${source}")
 string(SHA256 source_hash "${source}")
 file(READ "${DUCK_VBLANK_FIX_DIR}/juce_VBlank_windows_8_0_5.cpp" fixed)
 string(SHA256 fixed_hash "${fixed}")
 if(source_hash STREQUAL fixed_hash)
  message(STATUS "Duck Pocket: Windows VBlank fix already applied")
  return()
 endif()
 if(source_hash STREQUAL "914e6119f3f6397a37f6e2ed41353987166b4a9623eb485359512579d934e60a")
  file(WRITE "${target}" "${fixed}")
  message(STATUS "Duck Pocket: applied official JUCE Windows VBlank starvation fix")
 elseif(source MATCHES "flagPaintPending" AND NOT source MATCHES "condvar.wait")
  message(STATUS "Duck Pocket: JUCE already includes non-catching-up Windows VBlank pacing")
 else()
  message(FATAL_ERROR "Unknown JUCE Windows VBlank source: refusing to overwrite it. Use JUCE 8.0.4 or a version containing the upstream pacing fix.")
 endif()
endfunction()
